export type V2DrugKind = "insulin" | "glp1ra";

export type V2DosingInterval = "daily" | "weekly";

export type V2DrugMaster = {
  id: string;
  name: string;
  kind: V2DrugKind;
  category: string;
  dosingInterval: V2DosingInterval;
  doseUnit: "単位" | "mg" | "ドーズ";
  amountPerItem: number;
  amountUnitLabel: string;
  itemUnitLabel: string;
  primingUnitsPerInjection: number;
  quantityBasis: "amount" | "doseCount";
  doseInputMode?: "threeDoses" | "none";
};

export const V2_DRUG_MASTERS: V2DrugMaster[] = [
  {
    id: "novorapid",
    name: "ノボラピッド（アスパルト）",
    kind: "insulin",
    category: "超速効型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "fiasp",
    name: "フィアスプ",
    kind: "insulin",
    category: "超速効型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "humalog",
    name: "ヒューマログ（リスプロ）",
    kind: "insulin",
    category: "超速効型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "lyumjev",
    name: "ルムジェブ",
    kind: "insulin",
    category: "超速効型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "apidra",
    name: "アピドラ",
    kind: "insulin",
    category: "超速効型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "novolin-r",
    name: "ノボリンR",
    kind: "insulin",
    category: "速効型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "humulin-r",
    name: "ヒューマリンR",
    kind: "insulin",
    category: "速効型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "novolin-n",
    name: "ノボリンN",
    kind: "insulin",
    category: "中間型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "humulin-n",
    name: "ヒューマリンN",
    kind: "insulin",
    category: "中間型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "lantus",
    name: "ランタス",
    kind: "insulin",
    category: "持効型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "lantus-xr",
    name: "ランタスXR",
    kind: "insulin",
    category: "持効型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 450,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 3,
    quantityBasis: "amount",
  },
  {
    id: "toujeo",
    name: "インスリングラルギンBS / グラルギン製剤",
    kind: "insulin",
    category: "持効型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "levemir",
    name: "レベミル",
    kind: "insulin",
    category: "持効型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "tresiba",
    name: "トレシーバ",
    kind: "insulin",
    category: "持効型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "awiqli-300",
    name: "アウィクリ 300単位",
    kind: "insulin",
    category: "週1回持効型",
    dosingInterval: "weekly",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 10,
    quantityBasis: "amount",
  },
  {
    id: "awiqli-700",
    name: "アウィクリ 700単位",
    kind: "insulin",
    category: "週1回持効型",
    dosingInterval: "weekly",
    doseUnit: "単位",
    amountPerItem: 700,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 10,
    quantityBasis: "amount",
  },
  {
    id: "novorapid-30mix",
    name: "ノボラピッド30ミックス",
    kind: "insulin",
    category: "混合型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "novorapid-50mix",
    name: "ノボラピッド50ミックス",
    kind: "insulin",
    category: "混合型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "novorapid-70mix",
    name: "ノボラピッド70ミックス",
    kind: "insulin",
    category: "混合型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "humalog-mix25",
    name: "ヒューマログミックス25",
    kind: "insulin",
    category: "混合型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "humalog-mix50",
    name: "ヒューマログミックス50",
    kind: "insulin",
    category: "混合型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "novolin-30r",
    name: "ノボリン30R",
    kind: "insulin",
    category: "混合型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "humulin-3-7",
    name: "ヒューマリン3/7",
    kind: "insulin",
    category: "混合型",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "ryzodeg",
    name: "ライゾデグ配合",
    kind: "insulin",
    category: "配合溶解",
    dosingInterval: "daily",
    doseUnit: "単位",
    amountPerItem: 300,
    amountUnitLabel: "単位",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "xultophy",
    name: "ゾルトファイ配合",
    kind: "glp1ra",
    category: "インスリン/GLP-1RA配合",
    dosingInterval: "daily",
    doseUnit: "ドーズ",
    amountPerItem: 300,
    amountUnitLabel: "ドーズ",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "soliqua",
    name: "ソリクア配合",
    kind: "glp1ra",
    category: "インスリン/GLP-1RA配合",
    dosingInterval: "daily",
    doseUnit: "ドーズ",
    amountPerItem: 300,
    amountUnitLabel: "ドーズ",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 2,
    quantityBasis: "amount",
  },
  {
    id: "victoza",
    name: "ビクトーザ",
    kind: "glp1ra",
    category: "GLP-1RA",
    dosingInterval: "daily",
    doseUnit: "mg",
    amountPerItem: 18,
    amountUnitLabel: "mg",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 0.12,
    quantityBasis: "amount",
  },
  {
    id: "trulicity",
    name: "トルリシティ",
    kind: "glp1ra",
    category: "GLP-1RA",
    dosingInterval: "weekly",
    doseUnit: "mg",
    amountPerItem: 0.75,
    amountUnitLabel: "mg",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 0,
    quantityBasis: "doseCount",
    doseInputMode: "none",
  },
  {
    id: "ozempic",
    name: "オゼンピック",
    kind: "glp1ra",
    category: "GLP-1RA",
    dosingInterval: "weekly",
    doseUnit: "mg",
    amountPerItem: 2,
    amountUnitLabel: "mg",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 0,
    quantityBasis: "amount",
  },
  {
    id: "mounjaro",
    name: "マンジャロ",
    kind: "glp1ra",
    category: "GIP/GLP-1RA",
    dosingInterval: "weekly",
    doseUnit: "mg",
    amountPerItem: 1,
    amountUnitLabel: "回分",
    itemUnitLabel: "本",
    primingUnitsPerInjection: 0,
    quantityBasis: "doseCount",
    doseInputMode: "none",
  },
];
